# Generated by Django 2.0.2 on 2018-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_menu_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_pwd', models.CharField(max_length=32)),
                ('user_menu', models.ManyToManyField(to='db.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(on_delete=None, to='db.SubMenu'),
        ),
    ]
