# Generated by Django 2.0.2 on 2018-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180509_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='sub_menu_alias',
            field=models.CharField(default=1, max_length=128, verbose_name='英文名'),
            preserve_default=False,
        ),
    ]
